[FIX] Add retry if first dashboard retrieval fails
nicolastakashi/cole pull request #9
Opened 2022-12-23 16:33 UTC by lmarques03

Occasionally when retrieving the dashboard information, an error would occur with the message:
` "msg="status: 404, body: {\"message\":\"Dashboard not found\"}"`

After some investigation it was concluded that the error occurred when the request to Grafana API coincided with the restart of Grafana pods. 
This PR adds a one-time retry if the GET request fails.

2022-12-28 16:20 UTC, nicolastakashi commented
Hey, @lmarques03 thanks for the contribution!
Can you elaborate a little bit more about this issue, looking at the description that you provided, seems to me that the dashboard doesn't exist, could it be an issue with the dashboard sync instead of the Grafana API?

2022-12-30 10:17 UTC, lmarques03 commented
Hello, @nicolastakashi.
It certainly could be, however from our side, every time the error was triggered it coincided with the restart of Grafana pods. As such, the error is only triggered very occasionally, which indicates that most of the times the dashboard sync is done correctly. Also, the error does not persist, and on the next API call everything works fine, and the dashboard is found.

Apart from all of this, I was not able to replicate the error in my local environment, even when importing the same dashboards as in prd.

2023-01-04 09:43 UTC, nicolastakashi commented
Hey, @lmarques03 thanks for the clarification.
Well since it's a transient issue in my view we can just check the error code and don't treat 404 as an error, this is a recurrent task, the next time the dashboards will be available and everything is ok.

WDT?

2023-01-04 13:26 UTC, lmarques03 commented
@nicolastakashi That sounds like a good idea. Would you prefer to mantain the retry (and do it only when the error is 404), or simply ignore the error altogether, and wait for the next iteration?

2023-01-12 10:36 UTC, lmarques03 commented
Hello @nicolastakashi. I changed the code to handle 404 as a warning. It should be fine now. Please review and let me know what you think.

2023-01-24 21:33 UTC, nicolastakashi reviewed
Since you're using continue you don't need the else on the if statement

2023-01-25 10:49 UTC, lmarques03 commented
Yeah that was dumb. I fixed it now.
If the dashboard retrieval results in an error, then it always continues to the next iteration. But it does not consider the 404 response as an error.

2023-01-25 13:11 UTC, nicolastakashi commented on internal/grafana/client.go
>  				logrus.Warn(err)
I would prefer something like that:

```go
if strings.Contains(err.Error(), "status: 404") {
    logrus.Warn(err)
    continue
} 

get_dashboard_error_total.Inc()
logrus.Error(err)
```

2023-01-25 13:13 UTC, nicolastakashi requested changes

2023-01-25 13:13 UTC, nicolastakashi commented on internal/grafana/client.go
>  			if strings.Contains(err.Error(), "status: 404") {
```go
if strings.Contains(err.Error(), "status: 404") {
  logrus.Warn(err)
  continue
}

get_dashboard_error_total.Inc()
logrus.Error(err)
continue
```

WDYT?

2023-01-25 14:15 UTC, lmarques03 commented on internal/grafana/client.go
>  			if strings.Contains(err.Error(), "status: 404") {
Yeah, looks good to me.
I just pushed the new version

2023-01-27 08:06 UTC, nicolastakashi approved these changes

2023-01-27 08:06 UTC, merged